// Generated by gencpp from file vpa_robot_decision/InterMng.msg
// DO NOT EDIT!


#ifndef VPA_ROBOT_DECISION_MESSAGE_INTERMNG_H
#define VPA_ROBOT_DECISION_MESSAGE_INTERMNG_H

#include <ros/service_traits.h>


#include <vpa_robot_decision/InterMngRequest.h>
#include <vpa_robot_decision/InterMngResponse.h>


namespace vpa_robot_decision
{

struct InterMng
{

typedef InterMngRequest Request;
typedef InterMngResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InterMng
} // namespace vpa_robot_decision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vpa_robot_decision::InterMng > {
  static const char* value()
  {
    return "13e12f4673c290ff3d20da14d75e339f";
  }

  static const char* value(const ::vpa_robot_decision::InterMng&) { return value(); }
};

template<>
struct DataType< ::vpa_robot_decision::InterMng > {
  static const char* value()
  {
    return "vpa_robot_decision/InterMng";
  }

  static const char* value(const ::vpa_robot_decision::InterMng&) { return value(); }
};


// service_traits::MD5Sum< ::vpa_robot_decision::InterMngRequest> should match
// service_traits::MD5Sum< ::vpa_robot_decision::InterMng >
template<>
struct MD5Sum< ::vpa_robot_decision::InterMngRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_robot_decision::InterMng >::value();
  }
  static const char* value(const ::vpa_robot_decision::InterMngRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_robot_decision::InterMngRequest> should match
// service_traits::DataType< ::vpa_robot_decision::InterMng >
template<>
struct DataType< ::vpa_robot_decision::InterMngRequest>
{
  static const char* value()
  {
    return DataType< ::vpa_robot_decision::InterMng >::value();
  }
  static const char* value(const ::vpa_robot_decision::InterMngRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vpa_robot_decision::InterMngResponse> should match
// service_traits::MD5Sum< ::vpa_robot_decision::InterMng >
template<>
struct MD5Sum< ::vpa_robot_decision::InterMngResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_robot_decision::InterMng >::value();
  }
  static const char* value(const ::vpa_robot_decision::InterMngResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_robot_decision::InterMngResponse> should match
// service_traits::DataType< ::vpa_robot_decision::InterMng >
template<>
struct DataType< ::vpa_robot_decision::InterMngResponse>
{
  static const char* value()
  {
    return DataType< ::vpa_robot_decision::InterMng >::value();
  }
  static const char* value(const ::vpa_robot_decision::InterMngResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VPA_ROBOT_DECISION_MESSAGE_INTERMNG_H
