// Generated by gencpp from file vpa_robot_decision/InterMngRequest.msg
// DO NOT EDIT!


#ifndef VPA_ROBOT_DECISION_MESSAGE_INTERMNGREQUEST_H
#define VPA_ROBOT_DECISION_MESSAGE_INTERMNGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vpa_robot_decision
{
template <class ContainerAllocator>
struct InterMngRequest_
{
  typedef InterMngRequest_<ContainerAllocator> Type;

  InterMngRequest_()
    : header()
    , robot_name()
    , last_inter_id(0)
    , curr_inter_id(0)  {
    }
  InterMngRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , last_inter_id(0)
    , curr_inter_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef int8_t _last_inter_id_type;
  _last_inter_id_type last_inter_id;

   typedef int8_t _curr_inter_id_type;
  _curr_inter_id_type curr_inter_id;





  typedef boost::shared_ptr< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InterMngRequest_

typedef ::vpa_robot_decision::InterMngRequest_<std::allocator<void> > InterMngRequest;

typedef boost::shared_ptr< ::vpa_robot_decision::InterMngRequest > InterMngRequestPtr;
typedef boost::shared_ptr< ::vpa_robot_decision::InterMngRequest const> InterMngRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator1> & lhs, const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.last_inter_id == rhs.last_inter_id &&
    lhs.curr_inter_id == rhs.curr_inter_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator1> & lhs, const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vpa_robot_decision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0441c86245f04f14f6cacbb94a77e326";
  }

  static const char* value(const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0441c86245f04f14ULL;
  static const uint64_t static_value2 = 0xf6cacbb94a77e326ULL;
};

template<class ContainerAllocator>
struct DataType< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vpa_robot_decision/InterMngRequest";
  }

  static const char* value(const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string robot_name\n"
"int8 last_inter_id\n"
"int8 curr_inter_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.last_inter_id);
      stream.next(m.curr_inter_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterMngRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vpa_robot_decision::InterMngRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vpa_robot_decision::InterMngRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "last_inter_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.last_inter_id);
    s << indent << "curr_inter_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.curr_inter_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VPA_ROBOT_DECISION_MESSAGE_INTERMNGREQUEST_H
