# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vpa_robot_interface/WheelsOmegaInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WheelsOmegaInfo(genpy.Message):
  _md5sum = "ba80e47329fa708db7e2fff0c002fd00"
  _type = "vpa_robot_interface/WheelsOmegaInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 omega_left_ref
float32 omega_left_sig
float32 omega_right_ref
float32 omega_right_sig"""
  __slots__ = ['omega_left_ref','omega_left_sig','omega_right_ref','omega_right_sig']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       omega_left_ref,omega_left_sig,omega_right_ref,omega_right_sig

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WheelsOmegaInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.omega_left_ref is None:
        self.omega_left_ref = 0.
      if self.omega_left_sig is None:
        self.omega_left_sig = 0.
      if self.omega_right_ref is None:
        self.omega_right_ref = 0.
      if self.omega_right_sig is None:
        self.omega_right_sig = 0.
    else:
      self.omega_left_ref = 0.
      self.omega_left_sig = 0.
      self.omega_right_ref = 0.
      self.omega_right_sig = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.omega_left_ref, _x.omega_left_sig, _x.omega_right_ref, _x.omega_right_sig))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.omega_left_ref, _x.omega_left_sig, _x.omega_right_ref, _x.omega_right_sig,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.omega_left_ref, _x.omega_left_sig, _x.omega_right_ref, _x.omega_right_sig))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.omega_left_ref, _x.omega_left_sig, _x.omega_right_ref, _x.omega_right_sig,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
