string      robot_name
int8        robot_id
int8[]      robot_route
float32     robot_v
float32     robot_p
float64[]   robot_coordinate
bool        robot_enter_conflict

# time info
float32     robot_enter_lane_time
float32     robot_estimated_arrive_conflict_time
float32     robot_arrival_conflict_time
float32     robot_enter_conflict_time
float32     robot_arrive_cp_time
float32     robot_exit_time