// Generated by gencpp from file vpa_robot_interface/LeftWheelT.msg
// DO NOT EDIT!


#ifndef VPA_ROBOT_INTERFACE_MESSAGE_LEFTWHEELT_H
#define VPA_ROBOT_INTERFACE_MESSAGE_LEFTWHEELT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vpa_robot_interface
{
template <class ContainerAllocator>
struct LeftWheelT_
{
  typedef LeftWheelT_<ContainerAllocator> Type;

  LeftWheelT_()
    : throttle_left(0.0)  {
    }
  LeftWheelT_(const ContainerAllocator& _alloc)
    : throttle_left(0.0)  {
  (void)_alloc;
    }



   typedef float _throttle_left_type;
  _throttle_left_type throttle_left;





  typedef boost::shared_ptr< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> const> ConstPtr;

}; // struct LeftWheelT_

typedef ::vpa_robot_interface::LeftWheelT_<std::allocator<void> > LeftWheelT;

typedef boost::shared_ptr< ::vpa_robot_interface::LeftWheelT > LeftWheelTPtr;
typedef boost::shared_ptr< ::vpa_robot_interface::LeftWheelT const> LeftWheelTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator1> & lhs, const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator2> & rhs)
{
  return lhs.throttle_left == rhs.throttle_left;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator1> & lhs, const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vpa_robot_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "928a92cec7d033a951a07e21e36af4f5";
  }

  static const char* value(const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x928a92cec7d033a9ULL;
  static const uint64_t static_value2 = 0x51a07e21e36af4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vpa_robot_interface/LeftWheelT";
  }

  static const char* value(const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 throttle_left\n"
;
  }

  static const char* value(const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeftWheelT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vpa_robot_interface::LeftWheelT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vpa_robot_interface::LeftWheelT_<ContainerAllocator>& v)
  {
    s << indent << "throttle_left: ";
    Printer<float>::stream(s, indent + "  ", v.throttle_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VPA_ROBOT_INTERFACE_MESSAGE_LEFTWHEELT_H
