// Generated by gencpp from file vpa_robot_task/AssignTask.msg
// DO NOT EDIT!


#ifndef VPA_ROBOT_TASK_MESSAGE_ASSIGNTASK_H
#define VPA_ROBOT_TASK_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <vpa_robot_task/AssignTaskRequest.h>
#include <vpa_robot_task/AssignTaskResponse.h>


namespace vpa_robot_task
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace vpa_robot_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vpa_robot_task::AssignTask > {
  static const char* value()
  {
    return "cdad0eb519e23dd2b5d3e4c2e2b7ecf6";
  }

  static const char* value(const ::vpa_robot_task::AssignTask&) { return value(); }
};

template<>
struct DataType< ::vpa_robot_task::AssignTask > {
  static const char* value()
  {
    return "vpa_robot_task/AssignTask";
  }

  static const char* value(const ::vpa_robot_task::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::vpa_robot_task::AssignTaskRequest> should match
// service_traits::MD5Sum< ::vpa_robot_task::AssignTask >
template<>
struct MD5Sum< ::vpa_robot_task::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_robot_task::AssignTask >::value();
  }
  static const char* value(const ::vpa_robot_task::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_robot_task::AssignTaskRequest> should match
// service_traits::DataType< ::vpa_robot_task::AssignTask >
template<>
struct DataType< ::vpa_robot_task::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::vpa_robot_task::AssignTask >::value();
  }
  static const char* value(const ::vpa_robot_task::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vpa_robot_task::AssignTaskResponse> should match
// service_traits::MD5Sum< ::vpa_robot_task::AssignTask >
template<>
struct MD5Sum< ::vpa_robot_task::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vpa_robot_task::AssignTask >::value();
  }
  static const char* value(const ::vpa_robot_task::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vpa_robot_task::AssignTaskResponse> should match
// service_traits::DataType< ::vpa_robot_task::AssignTask >
template<>
struct DataType< ::vpa_robot_task::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::vpa_robot_task::AssignTask >::value();
  }
  static const char* value(const ::vpa_robot_task::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VPA_ROBOT_TASK_MESSAGE_ASSIGNTASK_H
