// Generated by gencpp from file vpa_robot_task/AssignTaskRequest.msg
// DO NOT EDIT!


#ifndef VPA_ROBOT_TASK_MESSAGE_ASSIGNTASKREQUEST_H
#define VPA_ROBOT_TASK_MESSAGE_ASSIGNTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vpa_robot_task
{
template <class ContainerAllocator>
struct AssignTaskRequest_
{
  typedef AssignTaskRequest_<ContainerAllocator> Type;

  AssignTaskRequest_()
    : robot_name()  {
    }
  AssignTaskRequest_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;





  typedef boost::shared_ptr< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskRequest_

typedef ::vpa_robot_task::AssignTaskRequest_<std::allocator<void> > AssignTaskRequest;

typedef boost::shared_ptr< ::vpa_robot_task::AssignTaskRequest > AssignTaskRequestPtr;
typedef boost::shared_ptr< ::vpa_robot_task::AssignTaskRequest const> AssignTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vpa_robot_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "889a1d391e36604c7ce79bf95df72cb6";
  }

  static const char* value(const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x889a1d391e36604cULL;
  static const uint64_t static_value2 = 0x7ce79bf95df72cb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vpa_robot_task/AssignTaskRequest";
  }

  static const char* value(const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_name\n"
;
  }

  static const char* value(const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vpa_robot_task::AssignTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VPA_ROBOT_TASK_MESSAGE_ASSIGNTASKREQUEST_H
